apiVersion: v1
kind: Service
metadata:
  name: django-spider
  namespace: default
spec:
  ports:
  - nodePort: 30026
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django-spider
  type: NodePort